name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: k1siv
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Moscow
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 14
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_habits: yes
          plugin_habits_from: 100
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_lines: yes
          plugin_traffic: yes
          plugin_stars: yes
          plugin_stars_limit: 4