name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        with:
          github_user_name: k1siv
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - uses: Platane/snk@v3
        with:
          github_user_name: k1siv
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          colors: "['#0d1117', '#8a2be2', '#8a2be2', '#6a1cb0']"
          
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          keep_files: true